<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

echo "/*=============================================================*/\n/* ShopEx database update script                               */\n/*                                                             */\n/*         Version:  from 13035 to 13936                       */\n/*   last Modified:  2008/08/29                                */\n/*=============================================================*/\n\n/*=";
echo "============================================================*/\n/* Create tables                                               */\n/*=============================================================*/\nCREATE TABLE `sdb_link` (\n  `link_id` mediumint(8) unsigned NOT NULL auto_increment,\n  `link_name` varchar(128) default NULL,\n  `href` varchar(255) default NULL,\n  `image_url` varchar(255) default NULL,\n  ";
echo "`orderlist` mediumint(8) default NULL,\n  `disabled` enum('true','false') default 'false',\n  PRIMARY KEY  (`link_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\n/*=============================================================*/\n/* New columns                                                 */\n/*=============================================================*/\nALTER TABLE `sdb_payments` ADD COLUMN `tr";
echo "ade_no` varchar(30) default NULL ;\nALTER TABLE `sdb_promotion` ADD COLUMN `pmt_ifsale` enum('true','false') NOT NULL default 'true' ;\nALTER TABLE `sdb_promotion` ADD COLUMN `pmt_distype` tinyint(3) unsigned NOT NULL default '0' ;\n\n/*=============================================================*/\n/* Modify columns                                              */\n/*===================================";
echo "==========================*/\nALTER TABLE `sdb_delivery_item` CHANGE COLUMN `item_type` `item_type` enum('goods','gift','pkg') NOT NULL default 'goods' ;\nALTER TABLE `sdb_event_hdls` CHANGE COLUMN `setting` `setting` longtext default NULL ;\nALTER TABLE `sdb_gift` CHANGE COLUMN `image_file` `image_file` longtext default NULL ;\nALTER TABLE `sdb_goods` CHANGE COLUMN `image_default` `image_default` lon";
echo "gtext default NULL ;\nALTER TABLE `sdb_goods` CHANGE COLUMN `image_file` `image_file` longtext default NULL ;\nALTER TABLE `sdb_goods_cat` CHANGE COLUMN `tabs` `tabs` longtext default NULL ;\nALTER TABLE `sdb_goods_cat` CHANGE COLUMN `finder` `finder` longtext default NULL ;\nALTER TABLE `sdb_goods_type` CHANGE COLUMN `alias` `alias` longtext default NULL ;\nALTER TABLE `sdb_logs` CHANGE COLUMN `logfor";
echo "man` `logforman` longtext default NULL ;\nALTER TABLE `sdb_logs` CHANGE COLUMN `logforcmp` `logforcmp` longtext default NULL ;\nALTER TABLE `sdb_members` CHANGE COLUMN `interest` `interest` longtext default NULL ;\nALTER TABLE `sdb_msgqueue` CHANGE COLUMN `data` `data` longtext default NULL ;\nALTER TABLE `sdb_order_log` CHANGE COLUMN `log_text` `log_text` longtext default NULL ;\nALTER TABLE `sdb_orde";
echo "rs` CHANGE COLUMN `tostr` `tostr` text default NULL ;\nALTER TABLE `sdb_orders` CHANGE COLUMN `memo` `memo` longtext default NULL ;\nALTER TABLE `sdb_package` CHANGE COLUMN `adminschema` `adminschema` longtext default NULL ;\nALTER TABLE `sdb_package` CHANGE COLUMN `shopaction` `shopaction` longtext default NULL ;\nALTER TABLE `sdb_pages` CHANGE COLUMN `page_content` `page_content` longtext default NU";
echo "LL ;\nALTER TABLE `sdb_payment_cfg` CHANGE COLUMN `des` `des` longtext default NULL ;\nALTER TABLE `sdb_products` CHANGE COLUMN `pdt_desc` `pdt_desc` longtext default NULL ;\nALTER TABLE `sdb_products` CHANGE COLUMN `props` `props` longtext default NULL ;\nALTER TABLE `sdb_refunds` CHANGE COLUMN `memo` `memo` longtext default NULL ;\nALTER TABLE `sdb_sendbox` CHANGE COLUMN `target` `target` longtext de";
echo "fault NULL ;\nALTER TABLE `sdb_systmpl` CHANGE COLUMN `content` `content` longtext default NULL ;\nALTER TABLE `sdb_themes` CHANGE COLUMN `config` `config` longtext default NULL ;\n";
?>
