<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

echo "/*=============================================================*/\n/* ShopEx database update script                               */\n/*                                                             */\n/*         Version:  from 13936 to 15211                       */\n/*   last Modified:  2008/11/03                                */\n/*=============================================================*/\n\n/*=";
echo "============================================================*/\n/* Create tables                                               */\n/*=============================================================*/\nCREATE TABLE `sdb_command_list` (\n  `cmd_action` varchar(100) NOT NULL,\n  `supplier_goods_id` int(11) NOT NULL,\n  `cmd_info` text,\n  `supplier_id` int(11) NOT NULL,\n  `cmd_lasttime` int(11) default NULL,\n ";
echo " `goods_name` varchar(255) default NULL,\n  PRIMARY KEY  (`cmd_action`,`supplier_goods_id`,`supplier_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_order_tmpl` (\n  `id` int(10) unsigned NOT NULL auto_increment,\n  `name` varchar(200) NOT NULL,\n  `content` text,\n  `intro` text,\n  `create_time` int(10) unsigned default NULL,\n  `update_time` int(10) unsigned default NULL,\n  `disable";
echo "d` enum('false','true') NOT NULL default 'false',\n  PRIMARY KEY  (`id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_supplier_goods_delete` (\n  `goods_id` int(11) NOT NULL,\n  `sync_status` enum('0','1') default '0',\n  `goods_name` varchar(255) default NULL,\n  PRIMARY KEY  (`goods_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_supplier_sync` (\n  `supplier_id` in";
echo "t(11) NOT NULL,\n  `last_time` int(11) default NULL,\n  PRIMARY KEY  (`supplier_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_wholesale` (\n  `ws_id` mediumint(8) unsigned NOT NULL auto_increment,\n  `ws_no` varchar(100) NOT NULL,\n  `ws_name` varchar(200) default NULL,\n  `ws_btime` int(10) default NULL,\n  `ws_etime` int(10) default NULL,\n  `ws_enable` enum('true','false') NOT NULL";
echo " default 'true',\n  `ws_belong` enum('0','1') NOT NULL default '0',\n  `ws_bind` tinyint(3) unsigned NOT NULL default '0',\n  `ws_params` longtext,\n  `ws_object` enum('goods','order') NOT NULL default 'order',\n  `ws_type` varchar(50) NOT NULL,\n  `ws_desc` longtext,\n  `ws_update_time` int(10) default '0',\n  `ws_order` int(10) unsigned NOT NULL default '0',\n  `disabled` enum('true','false') NOT NULL de";
echo "fault 'false',\n  PRIMARY KEY  (`ws_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_ws_goods` (\n  `ws_id` mediumint(8) unsigned NOT NULL,\n  `goods_id` mediumint(8) unsigned NOT NULL default '0',\n  PRIMARY KEY  (`goods_id`,`ws_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_ws_goods_cat` (\n  `ws_id` mediumint(8) unsigned NOT NULL,\n  `cat_id` mediumint(8) unsigne";
echo "d NOT NULL default '0',\n  `brand_id` mediumint(8) unsigned NOT NULL default '0',\n  PRIMARY KEY  (`cat_id`,`brand_id`,`ws_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\n/*=============================================================*/\n/* New columns                                                 */\n/*=============================================================*/\nALTER TABLE `sdb_brand` ADD COLU";
echo "MN `supplier_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_brand` ADD COLUMN `supplier_brand_id` mediumint(8) unsigned default NULL default '0' ;\nALTER TABLE `sdb_dly_area` ADD COLUMN `ordernum` smallint(4) unsigned default NULL ;\nALTER TABLE `sdb_dly_corp` ADD COLUMN `ordernum` smallint(4) unsigned default NULL ;\nALTER TABLE `sdb_dly_corp` ADD COLUMN `website` varchar(200) default NUL";
echo "L ;\nALTER TABLE `sdb_dly_h_area` ADD COLUMN `ordernum` smallint(4) unsigned default NULL ;\nALTER TABLE `sdb_dly_type` ADD COLUMN `corp_id` int(10) default NULL ;\nALTER TABLE `sdb_goods` ADD COLUMN `supplier_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_goods` ADD COLUMN `supplier_goods_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_goods` ADD COLUMN `goods_info_update_status";
echo "` enum('true','false') default NULL default 'false' ;\nALTER TABLE `sdb_goods` ADD COLUMN `stock_update_status` enum('true','false') default NULL default 'false' ;\nALTER TABLE `sdb_goods` ADD COLUMN `marketable_update_status` enum('true','false') default NULL default 'false' ;\nALTER TABLE `sdb_goods` ADD COLUMN `img_update_status` enum('true','false') default NULL default 'false' ;\nALTER TABLE `sdb";
echo "_goods_cat` ADD COLUMN `supplier_id` char(10) default NULL ;\nALTER TABLE `sdb_goods_cat` ADD COLUMN `supplier_cat_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_goods_type` ADD COLUMN `supplier_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_goods_type` ADD COLUMN `supplier_type_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_orders` ADD COLUMN `print_status` tinyint";
echo "(3) unsigned NOT NULL default '0' ;\nALTER TABLE `sdb_payment_cfg` ADD COLUMN `orderlist` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_payments` ADD COLUMN `cur_money` decimal(20,3) NOT NULL default '0.000' ;\n\n/*=============================================================*/\n/* Modify columns                                              */\n/*================================================";
echo "=============*/\nALTER TABLE `sdb_dly_type` CHANGE COLUMN `ordernum` `ordernum` smallint(4) default NULL default '0' ;\nALTER TABLE `sdb_goods` CHANGE COLUMN `price` `price` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_goods` CHANGE COLUMN `count_stat` `count_stat` text default NULL ;\nALTER TABLE `sdb_link` CHANGE COLUMN `href` `href` varchar(255) default NULL ;\nALTER TABLE `sdb_order_i";
echo "tems` CHANGE COLUMN `price` `price` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_orders` CHANGE COLUMN `cost_item` `cost_item` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_orders` CHANGE COLUMN `total_amount` `total_amount` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_orders` CHANGE COLUMN `final_amount` `final_amount` decimal(20,3) NOT NULL default '0.000' ;";
echo "\nALTER TABLE `sdb_payments` CHANGE COLUMN `money` `money` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_payments` CHANGE COLUMN `status` `status` enum('succ','failed','cancel','error','progress','invalid','timeout','ready') NOT NULL default 'ready' ;\nALTER TABLE `sdb_products` CHANGE COLUMN `price` `price` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_refunds` CHANGE COLUMN";
echo " `money` `money` decimal(20,3) NOT NULL default '0.000' ;\n\n/*=============================================================*/\n/* Index                                                       */\n/*=============================================================*/\n\n/*=============================================================*/\n/* Drop tables                                                 */\n/*========";
echo "=====================================================*/\n\n/*=============================================================*/\n/* Drop fields                                                 */\n/*=============================================================*/\nALTER TABLE `sdb_brand` DROP `s_brand_id`;\nALTER TABLE `sdb_goods` DROP `s_goods_id`;\nALTER TABLE `sdb_goods_cat` DROP `s_cat_id`;\nALTER TABLE `s";
echo "db_goods_type` DROP `s_type_id`;\n\n/*=============================================================*/\n/* Drop index                                                  */\n/*=============================================================*/\nALTER TABLE `sdb_gnotify` DROP INDEX `index_2`, ADD INDEX `index_2` USING BTREE(`goods_id`, `product_id`, `member_id`);\nupdate sdb_payment_cfg set pay_type = LOWER(pay_";
echo "type);\n";
?>
