<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

echo "/*=============================================================*/\n/* ShopEx database update script                               */\n/*                                                             */\n/*         Version:  from 16587 to 18137                       */\n/*   last Modified:  2009/01/13                                */\n/*=============================================================*/\n\n/*=";
echo "============================================================*/\n/* Create tables                                               */\n/*=============================================================*/\nCREATE TABLE `sdb_admin_roles` (\n  `role_id` int(10) unsigned NOT NULL auto_increment,\n  `role_name` varchar(100) NOT NULL default '',\n  `role_memo` text NOT NULL,\n  `disabled` enum('true','false') NOT NUL";
echo "L default 'false',\n  PRIMARY KEY  (`role_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_goods_keywords` (\n  `goods_id` mediumint(8) unsigned NOT NULL,\n  `keyword` varchar(40) NOT NULL default '',\n  PRIMARY KEY  (`keyword`,`goods_id`),\n  KEY `fk_idx_goods_keywords` (`goods_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_goods_spec_index` (\n  `type_id` mediumin";
echo "t(8) unsigned NOT NULL default '0',\n  `spec_id` mediumint(8) unsigned NOT NULL default '0',\n  `spec_value_id` mediumint(8) unsigned NOT NULL default '0',\n  `spec_value` varchar(100) default NULL,\n  `goods_id` mediumint(8) unsigned NOT NULL default '0',\n  `product_id` mediumint(8) unsigned NOT NULL default '0',\n  PRIMARY KEY  (`type_id`,`spec_id`,`spec_value_id`,`goods_id`,`product_id`)\n)type = MyI";
echo "SAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_goods_virtual_cat` (\n  `virtual_cat_id` mediumint(8) unsigned NOT NULL auto_increment,\n  `virtual_cat_name` varchar(100) NOT NULL,\n  `filter` longtext,\n  `addon` longtext,\n  `type_id` mediumint(8) unsigned default NULL,\n  `disabled` enum('false','true') NOT NULL default 'false',\n  `parent_id` mediumint(8) unsigned default '0',\n  `cat_id` mediumint";
echo "(8) unsigned default NULL,\n  `p_order` mediumint(8) unsigned default NULL,\n  `cat_path` varchar(100) default ',',\n  `child_count` mediumint(8) unsigned default '0',\n  PRIMARY KEY  (`virtual_cat_id`),\n  KEY `ind_disabled` (`disabled`),\n  KEY `ind_p_order` (`p_order`),\n  KEY `ind_cat_path` (`cat_path`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_lnk_acts` (\n  `role_id` int(10) unsi";
echo "gned NOT NULL,\n  `action_id` int(10) unsigned NOT NULL,\n  PRIMARY KEY  (`role_id`,`action_id`),\n  KEY `fk_reference_11` (`role_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_lnk_roles` (\n  `op_id` mediumint(8) unsigned NOT NULL,\n  `role_id` int(10) unsigned NOT NULL,\n  PRIMARY KEY  (`op_id`,`role_id`),\n  KEY `fk_reference_10` (`role_id`),\n  KEY `fk_reference_8` (`op_id`)\n)type ";
echo "= MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_member_attr` (\n  `attr_id` int(10) unsigned NOT NULL auto_increment,\n  `attr_name` varchar(20) NOT NULL default '',\n  `attr_type` varchar(20) NOT NULL default '',\n  `attr_required` enum('true','false') NOT NULL default 'false',\n  `attr_search` enum('true','false') NOT NULL default 'false',\n  `attr_option` text,\n  `attr_valtype` varchar(20) NO";
echo "T NULL default '',\n  `disabled` enum('true','false') NOT NULL default 'false',\n  `attr_tyname` varchar(20) NOT NULL default '',\n  `attr_group` varchar(20) NOT NULL default '',\n  `attr_show` enum('true','false') NOT NULL default 'true',\n  `attr_order` int(10) unsigned NOT NULL default '0',\n  PRIMARY KEY  (`attr_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_member_dealer` (\n  `m";
echo "ember_id` mediumint(8) NOT NULL auto_increment,\n  `dealer_site` varchar(200) NOT NULL,\n  `dealer_site_name` varchar(200) NOT NULL,\n  `dealer_logo` varchar(200) NOT NULL,\n  `dealer_consignee` varchar(200) NOT NULL,\n  `dealer_phone` varchar(200) NOT NULL,\n  `dealer_mobile` varchar(200) NOT NULL,\n  `dealer_area` varchar(255) NOT NULL,\n  `dealer_add` varchar(255) NOT NULL,\n  `dealer_zip` varchar(20) N";
echo "OT NULL,\n  `dealer_email` varchar(255) NOT NULL,\n  PRIMARY KEY  (`member_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_member_mattrvalue` (\n  `attr_id` int(10) unsigned NOT NULL default '0',\n  `member_id` mediumint(8) unsigned NOT NULL default '0',\n  `value` varchar(100) NOT NULL default '',\n  `id` int(10) unsigned NOT NULL auto_increment,\n  PRIMARY KEY  (`id`),\n  KEY `fk_refe";
echo "rence_12` (`attr_id`),\n  KEY `fk_reference_54` (`member_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_sell_logs` (\n  `log_id` mediumint(8) NOT NULL auto_increment,\n  `member_id` mediumint(8) NOT NULL default '0',\n  `name` varchar(50) default '',\n  `price` decimal(20,3) default '0.000',\n  `product_id` mediumint(8) NOT NULL default '0',\n  `goods_id` mediumint(8) unsigned NOT NUL";
echo "L,\n  `product_name` varchar(200) default '',\n  `pdt_desc` varchar(200) default '',\n  `number` int(10) default '0',\n  `createtime` int(10) default NULL,\n  PRIMARY KEY  (`log_id`),\n  KEY `idx_goods_id` (`member_id`,`product_id`,`goods_id`),\n  KEY `fk_idx_goods_sell_logs` (`goods_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\n/*=============================================================*/\n/* New ";
echo "columns                                                 */\n/*=============================================================*/\nALTER TABLE `sdb_advance_freeze` ADD COLUMN `freeze_money` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_advance_freeze` ADD COLUMN `thaw_money` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_advance_freeze` ADD COLUMN `created` int(10) NOT NULL defaul";
echo "t '' ;\nALTER TABLE `sdb_advance_freeze` ADD COLUMN `shop_message` varchar(255) default NULL ;\nALTER TABLE `sdb_advance_freeze` ADD COLUMN `disabled` enum('true','false') default NULL default 'false' ;\nALTER TABLE `sdb_goods` ADD COLUMN `cost` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_goods_cat` ADD COLUMN `child_count` mediumint(8) unsigned NOT NULL default '0' ;\nALTER TABLE `sdb_g";
echo "oods_type` ADD COLUMN `spec` longtext default NULL ;\nALTER TABLE `sdb_member_lv` ADD COLUMN `limit_order_money` int(11) NOT NULL default '0' ;\nALTER TABLE `sdb_member_lv` ADD COLUMN `apply_limit_quantity` enum('true','false') NOT NULL default 'true' ;\nALTER TABLE `sdb_member_lv` ADD COLUMN `show_other_price` enum('true','false') NOT NULL default 'true' ;\nALTER TABLE `sdb_member_lv` ADD COLUMN `ord";
echo "er_limit` tinyint(1) NOT NULL default '0' ;\nALTER TABLE `sdb_member_lv` ADD COLUMN `order_limit_price` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_member_lv` ADD COLUMN `lv_remark` text default NULL ;\nALTER TABLE `sdb_members` ADD COLUMN `advance_freeze` decimal(20,3) NOT NULL default '0.000' ;\nALTER TABLE `sdb_members` ADD COLUMN `remark` text default NULL ;\nALTER TABLE `sdb_members";
echo "` ADD COLUMN `role_type` enum('wholesale','dealer') NOT NULL default 'wholesale' ;\nALTER TABLE `sdb_message` ADD COLUMN `msg_ip` varchar(20) NOT NULL default '' ;\nALTER TABLE `sdb_message` ADD COLUMN `msg_type` enum('default','payment') NOT NULL default 'default' ;\nALTER TABLE `sdb_operators` ADD COLUMN `lastip` varchar(20) NOT NULL default '' ;\nALTER TABLE `sdb_operators` ADD COLUMN `logincount` ";
echo "mediumint(8) unsigned NOT NULL default '0' ;\nALTER TABLE `sdb_operators` ADD COLUMN `op_no` varchar(50) NOT NULL default '' ;\nALTER TABLE `sdb_operators` ADD COLUMN `department` varchar(50) NOT NULL default '' ;\nALTER TABLE `sdb_operators` ADD COLUMN `memo` text default NULL ;\nALTER TABLE `sdb_order_log` ADD COLUMN `behavior` varchar(20) default NULL default '' ;\nALTER TABLE `sdb_order_log` ADD CO";
echo "LUMN `result` enum('success','failure') default NULL default 'success' ;\nALTER TABLE `sdb_orders` ADD COLUMN `mark_text` longtext default NULL ;\nALTER TABLE `sdb_orders` ADD COLUMN `last_change_time` int(11) NOT NULL default '0' ;\nALTER TABLE `sdb_orders` ADD COLUMN `use_registerinfo` char(10) default NULL default 'false' ;\n\n/*=============================================================*/\n/* Modi";
echo "fy columns                                              */\n/*=============================================================*/\nALTER TABLE `sdb_advance_freeze` CHANGE COLUMN `member_id` `member_id` mediumint(8) NOT NULL default '' ;\nALTER TABLE `sdb_operators` CHANGE COLUMN `disabled` `disabled` enum('false','true') NOT NULL default 'false' ;\nALTER TABLE `sdb_return_product` CHANGE COLUMN `image_fil";
echo "e` `image_file` varchar(255) NOT NULL default '' ;\nALTER TABLE `sdb_wholesale_single` CHANGE COLUMN `wss_name` `wss_name` varchar(255) default NULL ;\n\n/*=============================================================*/\n/* Index                                                       */\n/*=============================================================*/\nALTER TABLE `sdb_spec_values` ADD INDEX `fk_referen";
echo "ce_60`(`spec_id`);\n\n/*=============================================================*/\n/* Drop tables                                                 */\n/*=============================================================*/\nDROP TABLE `sdb_member_info`;\n\n/*=============================================================*/\n/* Drop fields                                                 */\n/*=================";
echo "============================================*/\nALTER TABLE `sdb_advance_freeze` DROP `money`;\nALTER TABLE `sdb_advance_freeze` DROP `start_time`;\nALTER TABLE `sdb_advance_freeze` DROP `end_time`;\nALTER TABLE `sdb_members` DROP `member_role`;\nALTER TABLE `sdb_members` DROP `member_role_state`;\nALTER TABLE `sdb_operators` DROP `role_id`;\n\n/*===========================================================";
echo "==*/\n/* Drop index                                                  */\n/*=============================================================*/\nALTER TABLE `sdb_spec_values` DROP INDEX `fk_spec`;\n\n";
?>
