<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

echo "/*=============================================================*/\n/* ShopEx database update script                               */\n/*                                                             */\n/*         Version:  from 18137 to 21246                       */\n/*   last Modified:  2009/03/14                                */\n/*=============================================================*/\n\n/*=";
echo "============================================================*/\n/* Create tables                                               */\n/*=============================================================*/\nCREATE TABLE `sdb_gimages` (\n  `gimage_id` mediumint(8) unsigned NOT NULL auto_increment,\n  `goods_id` mediumint(8) unsigned default NULL,\n  `is_remote` enum('true','false') NOT NULL default 'false',\n  `so";
echo "urce` varchar(255) NOT NULL,\n  `orderby` tinyint(3) unsigned NOT NULL default '0',\n  `src_size_width` int(10) unsigned NOT NULL,\n  `src_size_height` int(10) unsigned NOT NULL,\n  `small` varchar(255) default NULL,\n  `big` varchar(255) default NULL,\n  `thumbnail` varchar(255) default NULL,\n  `up_time` int(10) unsigned NOT NULL,\n  PRIMARY KEY  (`gimage_id`),\n  KEY `fk_fk_gimages` (`goods_id`)\n)type =";
echo " MyISAM DEFAULT CHARACTER SET utf8;\n\nALTER TABLE `sdb_gimages` CHANGE COLUMN `source` `source` varchar(255) NULL ;\nALTER TABLE `sdb_gimages` CHANGE COLUMN `small` `small` varchar(255) NULL ;\nALTER TABLE `sdb_gimages` CHANGE COLUMN `big` `big` varchar(255) NULL ;\nALTER TABLE `sdb_gimages` CHANGE COLUMN `thumbnail` `thumbnail` varchar(255) NULL ;\nALTER TABLE `sdb_gimages` CHANGE COLUMN `orderby` `or";
echo "derby` tinyint(3) unsigned NOT NULL default '0' ;\n\n\nCREATE TABLE `sdb_goods_type_spec` (\n  `spec_id` mediumint(8) unsigned default '0',\n  `type_id` mediumint(8) unsigned default '0',\n  `spec_style` enum('select','flat','disabled') NOT NULL default 'flat',\n  KEY `fk_spec_type` (`spec_id`),\n  KEY `fk_type_spec` (`type_id`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\nCREATE TABLE `sdb_status` (\n  `st";
echo "atus_key` varchar(20) NOT NULL,\n  `date_affect` date NOT NULL default '0000-00-00',\n  `status_value` varchar(100) NOT NULL default '0',\n  `last_update` int(10) unsigned NOT NULL,\n  PRIMARY KEY  (`status_key`,`date_affect`)\n)type = MyISAM DEFAULT CHARACTER SET utf8;\n\n/*=============================================================*/\n/* New columns                                                 */\n/";
echo "*=============================================================*/\nALTER TABLE `sdb_dly_h_area` DROP INDEX `PRIMARY`;\nALTER TABLE `sdb_dly_h_area` ADD COLUMN `dha_id` mediumint(8) unsigned NOT NULL auto_increment PRIMARY KEY;\nALTER TABLE `sdb_dly_h_area` ADD COLUMN `areaname_group` longtext default NULL ;\nALTER TABLE `sdb_dly_h_area` ADD COLUMN `areaid_group` longtext default NULL ;\nALTER TABLE `sdb";
echo "_dly_h_area` ADD COLUMN `config` varchar(255) default NULL ;\nALTER TABLE `sdb_dly_type` ADD COLUMN `dt_config` longtext default NULL ;\nALTER TABLE `sdb_dly_type` ADD COLUMN `dt_expressions` longtext default NULL ;\nALTER TABLE `sdb_dly_type` ADD COLUMN `dt_status` mediumint(1) unsigned default NULL ;\nALTER TABLE `sdb_goods` ADD COLUMN `spec_desc` longtext default NULL ;\nALTER TABLE `sdb_members` AD";
echo "D COLUMN `remark_type` varchar(2) NOT NULL default 'b1' ;\nALTER TABLE `sdb_orders` ADD COLUMN `mark_type` varchar(2) NOT NULL default 'b1' ;\nALTER TABLE `sdb_regions` ADD COLUMN `region_path` varchar(255) default NULL ;\nALTER TABLE `sdb_regions` ADD COLUMN `region_grade` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_regions` ADD COLUMN `ordernum` mediumint(8) unsigned default NULL ;\nALTER ";
echo "TABLE `sdb_sitemaps` ADD COLUMN `child_count` mediumint(4) default NULL ;\nALTER TABLE `sdb_spec_values` DROP INDEX `PRIMARY`;\nALTER TABLE `sdb_spec_values` ADD COLUMN `spec_value_id` mediumint(8) unsigned NOT NULL auto_increment PRIMARY KEY;\nALTER TABLE `sdb_spec_values` ADD COLUMN `spec_image` varchar(255) NOT NULL default '' ;\nALTER TABLE `sdb_specification` ADD COLUMN `spec_show_type` enum('sel";
echo "ect','flat') NOT NULL default 'flat' ;\nALTER TABLE `sdb_specification` ADD COLUMN `spec_type` enum('text','image') NOT NULL default 'text' ;\nALTER TABLE `sdb_specification` ADD COLUMN `spec_memo` varchar(50) NOT NULL default '' ;\nALTER TABLE `sdb_specification` ADD COLUMN `disabled` enum('true','false') NOT NULL default 'false' ;\n\n/*=============================================================*/\n/";
echo "* Modify columns                                              */\n/*=============================================================*/\nUPDATE `sdb_spec_values` SET `p_order` = '50' WHERE `p_order` IS NULL;\nUPDATE `sdb_specification` SET `p_order` = '0' WHERE `p_order` IS NULL;\n\nALTER TABLE `sdb_coupons` CHANGE COLUMN `cpns_type` `cpns_type` enum('0','1','2') NOT NULL default '1' ;\nALTER TABLE `sdb_dly";
echo "_h_area` CHANGE COLUMN `dt_id` `dt_id` mediumint(8) unsigned default NULL ;\nALTER TABLE `sdb_dly_h_area` CHANGE COLUMN `area_id` `area_id` mediumint(6) unsigned default NULL default '0' ;\nALTER TABLE `sdb_dly_h_area` CHANGE COLUMN `price` `price` varchar(100) default NULL default '0' ;\n\nALTER TABLE `sdb_goods` DROP COLUMN `ws_policy`;\nALTER TABLE `sdb_goods` ADD COLUMN `ws_policy` enum('11','01') ";
echo "NOT NULL default '01' ;\nALTER TABLE `sdb_goods_spec_index` CHANGE COLUMN `spec_value` `spec_value` varchar(100) NOT NULL default '' ;\nALTER TABLE `sdb_orders` CHANGE COLUMN `use_registerinfo` `use_registerinfo` enum('true','false') default NULL default 'false' ;\nALTER TABLE `sdb_spec_values` CHANGE COLUMN `spec_id` `spec_id` mediumint(8) unsigned NOT NULL default '0' ;\nALTER TABLE `sdb_spec_values";
echo "` CHANGE COLUMN `p_order` `p_order` mediumint(8) unsigned NOT NULL default '50' ;\nALTER TABLE `sdb_specification` CHANGE COLUMN `spec_id` `spec_id` mediumint(8) unsigned NOT NULL auto_increment;\nALTER TABLE `sdb_specification` CHANGE COLUMN `p_order` `p_order` mediumint(8) unsigned NOT NULL default '0' ;\n\n/*=============================================================*/\n/* Index                   ";
echo "                                    */\n/*=============================================================*/\nALTER TABLE `sdb_goods_spec_index` DROP INDEX `PRIMARY`;\nALTER TABLE `sdb_goods_spec_index` ADD CONSTRAINT  `PRIMARY` PRIMARY KEY CLUSTERED(`spec_value_id`,`product_id`);\nALTER TABLE `sdb_goods_spec_index` ADD INDEX `type_specvalue_index`(`type_id`,`spec_value_id`,`goods_id`);\nALTER TABLE `sdb_";
echo "goods_spec_index` ADD INDEX `fk_spec_goods_index`(`goods_id`);\nALTER TABLE `sdb_goods_spec_index` ADD INDEX `fk_spec_index`(`spec_id`);\nALTER TABLE `sdb_goods_spec_index` ADD INDEX `fk_spec_products`(`product_id`);\nALTER TABLE `sdb_goods_spec_index` ADD INDEX `fk_spec_type_index`(`type_id`);\nALTER TABLE `sdb_goods_spec_index` ADD INDEX `fk_spec_value_index`(`spec_value_id`);\nALTER TABLE `sdb_spec_";
echo "values` ADD INDEX `fk_spec_value`(`spec_id`);\n\n/*=============================================================*/\n/* Drop tables                                                 */\n/*=============================================================*/\n\n/*=============================================================*/\n/* Drop fields                                                 */\n/*====================";
echo "=========================================*/\nALTER TABLE `sdb_member_lv` DROP `limit_order_money`;\nALTER TABLE `sdb_member_lv` DROP `apply_limit_quantity`;\n\n/*=============================================================*/\n/* Drop index                                                  */\n/*=============================================================*/\nALTER TABLE `sdb_spec_values` DROP INDEX `fk_r";
echo "eference_60`;\n\n/*=============================================================*/\n/* Manual anybody                                                  */\n/*=============================================================*/\nALTER TABLE `sdb_products` CHANGE `cost` `cost` DECIMAL( 20, 3 ) NULL DEFAULT '0';\nUPDATE `sdb_products` SET `cost` = 0 WHERE `cost` IS NULL;\n";
?>
